### ISSUE TITLE
Encountered a Leak

### ISSUE THREAD

**Issue by dlet24** [javiersantos/AppUpdater#32]
I used [StrictMode](https://developer.android.com/reference/android/os/StrictMode.html) while testing my app and I received an error. I think HTTP connection was not closed.

**Error Log:**

`E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                      java.lang.Throwable: Explicit termination method 'close' not called
                                                                          at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                                          at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:288)
                                                                          at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:103)
                                                                          at com.android.okhttp.Connection.connect(Connection.java:143)
                                                                          at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
                                                                          at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
                                                                          at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
                                                                          at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
                                                                          at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
                                                                          at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
                                                                          at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114)
                                                                          at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
                                                                          at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java)
                                                                          at com.github.javiersantos.appupdater.UtilsLibrary.getLatestAppVersionHttp(UtilsLibrary.java:122)
                                                                          at com.github.javiersantos.appupdater.UtilsAsync$LatestAppVersion.doInBackground(UtilsAsync.java:59)
                                                                          at com.github.javiersantos.appupdater.UtilsAsync$LatestAppVersion.doInBackground(UtilsAsync.java:13)
                                                                          at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                          at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                          at java.lang.Thread.run(Thread.java:818)`

**Comment by javiersantos** [comment]
The latest update should fix this leak: https://github.com/javiersantos/AppUpdater/commit/064daf1ea115dda813f19239eb1d4155562f22e0. Thank you for letting me know!

```Javascript
dependencies {
    compile 'com.github.javiersantos:AppUpdater:2.2'
}
```
