### ISSUE TITLE
java.net.SocketTimeoutException

### ISSUE THREAD

**Issue by garik888** [javiersantos/AppUpdater#56]
It seems that the timeout causes an error because of which my app closes.

`Caused by: java.lang.RuntimeException: java.net.SocketTimeoutException: failed to connect to sit30.ru/212.47.233.170 (port 80) after 90000ms
    at com.github.javiersantos.appupdater.RssParser.getInputStream(RssParser.java:63)
    at com.github.javiersantos.appupdater.RssParser.parse(RssParser.java:35)
    at com.github.javiersantos.appupdater.UtilsLibrary.getLatestAppVersionXml(UtilsLibrary.java:247)
    at com.github.javiersantos.appupdater.UtilsAsync$LatestAppVersion.doInBackground(UtilsAsync.java:57)
    at com.github.javiersantos.appupdater.UtilsAsync$LatestAppVersion.doInBackground(UtilsAsync.java:13)
    at android.os.AsyncTask$2.call(AsyncTask.java:292)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    ... 4 more
 Caused by: java.net.SocketTimeoutException: failed to connect to sit30.ru/212.47.233.170 (port 80) after 90000ms
    at libcore.io.IoBridge.connectErrno(IoBridge.java:189)
    at libcore.io.IoBridge.connect(IoBridge.java:127)
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:188)
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:461)
    at java.net.Socket.connect(Socket.java:918)
    at com.android.okhttp.internal.Platform.connectSocket(Platform.java:174)
    at com.android.okhttp.Connection.connect(Connection.java:152)
    at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:282)
    at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:216)
    at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:391)
    at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:341)
    at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:199)
    at com.github.javiersantos.appupdater.RssParser.getInputStream(RssParser.java:58)`

**Comment by Khoosham** [comment]
use try and catch 
you can display a toast message in the catch its timeout error so internet connectivity issues

**Comment by garik888** [comment]
Thanks, but I already wrote a module to check the version. You decide the problem moments too long. Why should I use try catch, if you have to manage the process ?!

**Comment by adiga-maf** [comment]
Agree with @garik888 , its supposed to have better handle
