### ISSUE TITLE
BadTokenException crash

### ISSUE THREAD

**Issue by gparigibini** [javiersantos/AppUpdater#66]
Hello,
I received many reports for the following crash.
When the update check finishes, if the bound context is not running anymore the app will crash and, being asynchronous, we can't catch it.
Unfortunately I don't know any clean countermeasure for this problem without modifying any other part of this library, so in my local copy I've used a big try-catch inside the onSuccess method. 

Thank you very much!

```
Fatal Exception: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@46a0ca5 is not valid; is your activity running?
       at android.view.ViewRootImpl.setView(ViewRootImpl.java:687)
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:288)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
       at android.app.Dialog.show(Dialog.java:312)
       at com.github.javiersantos.appupdater.AppUpdater$1.onSuccess(AppUpdater.java:309)
       at com.github.javiersantos.appupdater.UtilsAsync$LatestAppVersion.onPostExecute(UtilsAsync.java:82)
```

**Comment by brunolopes446** [comment]
I also have this problem. Could you please provide a release asap?

**Comment by javiersantos** [comment]
Could you please update to the latest update? Thank you.

```Javascript
dependencies {
    compile 'com.github.javiersantos:AppUpdater:2.5.1'
}
```
