### ISSUE TITLE
Fatal Error seeing in Fabric

### ISSUE THREAD

**Issue by KennyGoers** [javiersantos/AppUpdater#71]
Seeing the following issue, possibly something going out of scope? At least need protection from the error when Activity/Context is invalid?

Seeing in 2.5.1 as well as earlier versions.

```
Fatal Exception: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@178ef1bd is not valid; is your activity running?
       at android.view.ViewRootImpl.setView(ViewRootImpl.java:579)
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:282)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
       at android.app.Dialog.show(Dialog.java:298)
       at com.github.javiersantos.appupdater.AppUpdater$1.onSuccess(AppUpdater.java:302)
       at com.github.javiersantos.appupdater.UtilsAsync$LatestAppVersion.onPostExecute(UtilsAsync.java:74)
       at com.github.javiersantos.appupdater.UtilsAsync$LatestAppVersion.onPostExecute(UtilsAsync.java:13)
       at android.os.AsyncTask.finish(AsyncTask.java:636)
       at android.os.AsyncTask.access$500(AsyncTask.java:177)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5333)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:940)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:735)
```

**Comment by javiersantos** [comment]
This issue should be fixed within the latest updates. The dialog is only displayed if the activity is still showing / active.
